#!/usr/bin/bash

podman run \
 	-v "${HOME}/.claude:/home/claude/.claude" \
	-v "${HOME}/.claude.json:/home/claude/.claude.json" \
	-v "${PWD}:${PWD}" \
	-w "$PWD" \
    -i \
    -t \
    --user claude \
     claude-box
